name: Deploy to EC2 with Docker

on:
  push:
    branches: [main, feat/#29-카페삭제관리자페이지]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build JAR
        run: ./gradlew clean build -x test

      - name: Copy jar to Docker context
        run: cp build/libs/TagCafe-0.0.1-SNAPSHOT.jar .

      - name: Upload jar to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "TagCafe-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/app/"

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/app
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d