name: Deploy to EC2

on:
  push:
    branches: [main]  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Build jar
        run: ./gradlew clean bootJar -x test
        
      - name: Check built jar exists
        run: ls -al build/libs
  
      - name: Copy jar to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: build/libs/TagCafe-0.0.1-SNAPSHOT.jar
          target: "/home/ec2-user/app"
          strip_components: 2

      - name: Generate .env file
        run: |
          echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
          echo "KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}" >> .env
          echo "SECURITY_JWT_SECRET=${{ secrets.SECURITY_JWT_SECRET }}" >> .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Copy .env to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
         host: ${{ secrets.EC2_HOST }}
         username: ec2-user
         key: ${{ secrets.EC2_KEY }}
         source: .env
         target: /home/ec2-user/app    

      - name: Run app on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            pkill -f 'jar' || true
            cd /home/ec2-user/app/build/libs
            nohup java -jar TagCafe-0.0.1-SNAPSHOT.jar > /home/ec2-user/app/app.log 2>&1 &
